version: "3.9"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  backend-django:
    build: .
    command: python manage.py runserver 0.0.0.0:8080
    ports:
      - "8000:8000"
    volumes:
    - .:/app
    depends_on:
      - db